name: Test_cocotb

on: [push]

jobs:
  test-suites:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test_vhdl
        run: |
          cd 2021/tb
          make TOPLEVEL_LANG=vhdl SIM=ghdl
      - name: Test_verilog
        run: |
          cd 2021/tb
          make TOPLEVEL_LANG=verilog SIM=icarus
